name: iOS CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"
        bundler-cache: true

    - name: Cache Fastlane
      uses: actions/cache@v2
      with:
          path: ~/.gem
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

    - name: Install dependencies
      run: |
        cd fastlane
        gem install bundler
        bundle install --without=documentation

    - name: Build and Test
      run: |
        xcodebuild -resolvePackageDependencies
        xcodebuild -project iDev.xcodeproj -scheme Release -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/iDev.xcarchive

    - name: Export .ipa
      run: |
        xcodebuild -exportArchive -archivePath $PWD/build/iDev.xcarchive -exportOptionsPlist ../Utils/export-options.plist -exportPath $PWD/build

    - name: Install Fastlane
      run: bundle exec fastlane init

    - name: Upload to TestFlight
      run: bundle exec fastlane pilot upload